### ISSUE TITLE
Approve clients if they have valid CFEngine keys

### ISSUE THREAD

**Issue by oyvindhagberg** [usit-gd/nivlheim#108]
- nivlheim-client må signere noe med privat nøkkel `/var/cfengine/ppkeys/localhost.priv` og oversende ifm at den ber om et sertifikat. Må også sende md5-digest av nøkkelen, den kan skaffes ved å kjøre `/var/cfengine/bin/cf-key -p /var/cfengine/ppkeys/localhost.pub`.
  - _Problem:_ `localhost.priv` er kryptert med en passphrase, hvor finner vi den?
- alternativt kan klienten bruke innholdet i `localhost.pub` som passphase for en symmetrisk krypteringsalgoritme. Da slipper vi å skaffe tilgang til privatnøkkelen. Om det er sikkert nok, kommer an på om det bare er CFEngine-serverne som har (eller kan skaffe seg) en kopi av den filen.
- nivlheim server må hente klientens public key fra en av CFEngine-serverne for å kunne verifisere signaturen. Den ligger som en fil under `/var/cfengine/ppkeys`.
  - _Problem:_ Hvordan skal Nivlheim få tilgang til disse filene?

**Comment by JarleB** [comment]
Sjekk https://github.com/werkt/cfengine-community/blob/master/src/crypto.c#L91 ;-)

**Comment by JarleB** [comment]
Ang distribusjon av pubkeys så er antakelig det enkleste at nivlheim-serveren legges inn i lista til distribusjonsscriptet som dister pubkeys mellom cfengine-serverene. @trondham Enig ?

**Comment by trondham** [comment]
> Ang distribusjon av pubkeys så er antakelig det enkleste at nivlheim-serveren legges inn i lista til distribusjonsscriptet som dister pubkeys mellom cfengine-serverene. @trondham Enig ?

Ja, det virker som den enkleste løsningen

**Comment by oyvindhagberg** [comment]
Siden maskiner nå skal kunne komme inn i Nivlheim på annet grunnlag enn ip-adressen, må systemet endres for at disse skal få et hostnavn i Nivlheim.

**Comment by oyvindhagberg** [comment]
Fixed in #135 and a23b0a3d3ebf1eb9c7c9392a75b0c279b8423b88
